### ISSUE TITLE
PySpaceMouse on MacOS ARM M1 

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/pySpaceMouse#10]
I have tried to install PySpaceMouse on MacOS M1, but it doesn`t work.
Is there anybody who fixed this issue?

I have installed `hidapi` trough `brew install hidapi`.
My result from [basicExample.py](https://github.com/JakubAndrysek/PySpaceMouse/blob/master/examples/basicExample.py) is there:
```bash
 ✘ kuba@pc  ~/Documents/git/kuba/pyspacemouse   master ±  python3.11 ./examples/basicExample.py
Traceback (most recent call last):
  File "/Users/kuba/Documents/git/kuba/pyspacemouse/./examples/basicExample.py", line 4, in <module>
    success = pyspacemouse.open()
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyspacemouse/pyspacemouse.py", line 703, in open
    all_devices = list_devices()
                  ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyspacemouse/pyspacemouse.py", line 643, in list_devices
    hid = Enumeration()
          ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/easyhid/easyhid.py", line 366, in __init__
    self.device_list = _hid_enumerate(vid, pid)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/easyhid/easyhid.py", line 428, in _hid_enumerate
    start = hidapi.hid_enumerate(vendor_id, product_id)
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function/symbol 'hid_enumerate' not found in library '<None>': dlsym(RTLD_DEFAULT, hid_enumerate): symbol not found
```

Related links:
- https://github.com/gl-sergei/u2f-token/issues/18
- https://github.com/earlephilhower/arduino-pico/issues/703

**Comment by misz11** [comment]
I recently had the same issue on my Macbook Pro Apple M1 (MacOS Ventura). The issue is that I installed my python environment with anaconda for x86_64 instead of arm M1.
Python runs without problem thanks to Rosetta. However, when python is loading library, it expects those library to be x86_64 as well. I found two ways to solve the issue:
1. Reinstall anaconda by using the version for arm M1 (by default it downloads the x86_64 version, simply scroll all the way down the page to have the full list)
2. Use a pre-compiled version of libhidapi.dylib for x86_64 by adding it to the PATH (here is the one I used:
[libhidapi.dylib.zip](https://github.com/JakubAndrysek/PySpaceMouse/files/11015808/libhidapi.dylib.zip)

**Comment by JakubAndrysek** [comment]
https://www.reddit.com/r/learnpython/comments/11ns21o/read_spacemouse_input_using_python/
https://forum.3dconnexion.com/viewtopic.php?f=23&t=50205

**Comment by consi** [comment]
Hey, I've managed to get it running by adding `/opt/homebrew/Cellar/hidapi/0.14.0/lib` to my `DYLD_LIBRARY_PATH`. (I run python with aarch64)

**Comment by JakubAndrysek** [comment]
Thanks, I will test it and your description in the main guide.

**Comment by JakubAndrysek** [comment]
> Hey, I've managed to get it running by adding `/opt/homebrew/Cellar/hidapi/0.14.0/lib` to my `DYLD_LIBRARY_PATH`. (I run python with aarch64)

Thanks a lot for your solution. I have tested it, and everything works perfectly.
I have also added it to the primary documentation.

**Comment by openSourcerer9000** [comment]
Had to also change the path here, pending this PR https://github.com/ahtn/python-easyhid/pull/6
