### ISSUE TITLE
Spacemouse bluetooth wireless (not supported?)

### ISSUE THREAD

**Issue by jagdeepsb** [JakubAndrysek/pySpaceMouse#28]
Hey I have a space mouse which I am trying to use with your repo:

I can see the device with `hidapitester`:
```
256F/C63A: 3Dconnexion - SpaceMouse Wireless BT
  vendorId:      0x256F
  productId:     0xC63A
```

However, `pyspacemouse` is telling me that no devices are connected. I'm suspecting that maybe this space mouse model isn't supported?
```
Available SpaceMouse devices:
- SpaceMouse Enterprise [VID: 0x256f, PID: 0xc633]
- SpaceExplorer [VID: 0x46d, PID: 0xc627]
- SpaceNavigator [VID: 0x46d, PID: 0xc626]
- SpaceMouse USB [VID: 0x256f, PID: 0xc641]
- SpaceMouse Compact [VID: 0x256f, PID: 0xc635]
- SpaceMouse Pro Wireless [VID: 0x256f, PID: 0xc632]
- SpaceMouse Pro [VID: 0x46d, PID: 0xc62b]
- SpaceMouse Wireless [VID: 0x256f, PID: 0xc62e]
- 3Dconnexion Universal Receiver [VID: 0x256f, PID: 0xc652]
- SpacePilot [VID: 0x46d, PID: 0xc625]
- SpacePilot Pro [VID: 0x46d, PID: 0xc629]
```

Wondering if maybe I need to connect the device in a different way (usb vs bluetooth)?
Any help would be appreciated.

**Comment by jagdeepsb** [comment]
update: I cloned the `SpaceMouse Wireless` --> `SpaceMouse Wireless [NEW]` entry and changed the product id to `0xC63A`
seems to be working!

**Comment by JakubAndrysek** [comment]
Could you please create PR with new fixed config. Thanks
