### ISSUE TITLE
roll/pitch/yaw Spacemouse Wireless

### ISSUE THREAD

**Issue by huggare** [JakubAndrysek/pySpaceMouse#6]
Dear Jakub,
Thank you for your great contribution!

I had some issues when I changed from USB to wireless Spacemouse, but I found the solution here (the byte-array issue that was solved here) I dont think it is implemented in the current version that is downloaded from PyPi however. 

My next issue is the fact that rotation doesnt show any reaction ( roll, pitch, yaw). I'm testing on a beaglebone blue running some new debian release.  I tried to change channels in the pyspacemouse.py similar to the wired versions, but no change there...

When I connect the device, i get 5 HID devices popping up..

Best regards
Viktor

**Comment by huggare** [comment]
Hello again!
I got help and we managed to find the issue:

From row 204:         
if self.connected:
            # read seven bytes from SpaceMouse
            ret = self.device.read(7)

This "7" needs to be a variable depending on if you have wireless or not, but i changed it to a hardcoded 13.

**Comment by JakubAndrysek** [comment]
Hi Viktor, 

thank you for report. Could you please create a pull request fixing your problem. I didn't have wireless 3D mouse to simulate your situation.

Best regards
Jacob
