### ISSUE TITLE
Latency of Data Reading

### ISSUE THREAD

**Issue by misz11** [JakubAndrysek/pySpaceMouse#9]
In a Python application with a SpaceMouse Wireless and SpaceMouse Compact we have very high delays when reading data.
We get the first values after initiating a movement after 100ms, but after reaching the zero position again it takes about 1-2 seconds until the values return to zero.
Is this problem known or are certain filters applied?
We are using the pyspacemouse package, and the 3 methods open(), read(), close().
Here is my code:
![Bildschirm­foto 2023-03-15 um 12 36 17](https://user-images.githubusercontent.com/101103674/225297773-0e9e408c-cb3d-400c-9012-c8b18da4c6f3.png)

Thank you very much for your support.

**Comment by JakubAndrysek** [comment]
Hi, I have tested latest version with Space mouse PRO and everything works smoothly. I am using Ubuntu 22 which works perfectly for me.

On which platform have you tested your code?

My library reads data from mouse directly from HID USB. In the background is only HID driver, that might be problematic and slow.

I haven't measured the time of read loop, but it is usually tens to hundreds of iterations per second.

**Comment by misz11** [comment]
I'm using MacOS Ventura in a virtual Conda environment.
Reading works really fast but the inputs are very long-lasting and take a long time to disappear.

![Bildschirm­foto 2023-03-16 um 09 24 17](https://user-images.githubusercontent.com/101103674/225557715-4a44160a-8b62-4993-8d81-16d5ce8ff399.png)
I was able to work around the problem by making a for loop around the reading function. But that's just a messy solution.
Then the inputs disappear faster and it is still possible to run the whileloop with 100Hz.

Is it possible that the problem is with the cache and all inputs must be read first (fist in first out)?
I did a quick test, my results attached.
[test.pdf](https://github.com/JakubAndrysek/PySpaceMouse/files/10988507/test.pdf)

**Comment by JakubAndrysek** [comment]
Thank you for your report.
My second PC is Macbook Pro M1. I haven't run the library on macOS yet.
I have tried to install hidapi through `brew install hidapi`, but it doesn`t work for me.
Is it necessary to add some file to system PATHs?

Could you please add more information about your installation to [README - Installation](https://github.com/JakubAndrysek/PySpaceMouse/blob/master/README.md)

**Comment by JakubAndrysek** [comment]
I have created a separate issue for MacOS M1 installation problem #10.

**Comment by JakubAndrysek** [comment]
I think it has been fixed with #10

**Comment by leonmkim** [comment]
I have the exact same issue as @misz11 in that it seems like `pyspacemouse.read()` gets spacemouse states off of some sort of FIFO buffer. Hence, `.read()` does not poll the latest spacemouse state and in any loop with some delay between the next `.read()` call, I start to see major latency from the current/actual and read spacemouse state. 

I've solved it for now by calling `.read()` as fast as possible in a separate process from the main, but I think it'd be much more intuitive if pyspacemouse handled it for me.

FWIW I'm on ubuntu 20.04 and installed using `pip install`, using version 1.1.4 according to the CLI.

**Comment by JakubAndrysek** [comment]
Hi, I know about this problem.
If you know how to fix it, feel free to create PR.
